model_path = "/home/student/Documents/AnonAI/face_detection/models/model-r100-arcface-ms1m-refine-v2/model-r100-ii/model"
image_path = "/home/student/Documents/AnonAI/face_detection/code/anonai-skupina1/test_images/family.jpg"
# video_path = "videos/china_man.mov"
# video_path = "videos/rabbit2.mp4"
video_path = "videos/gilmore_girls_a_second_film_by_kirk.mp4"